version: '3.8'
services:

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db_datas:/var/lib/postgresql/data/
    env_file:
      - "./.env"

  backend:
    build: app
    env_file:
      - "./.env"
    volumes:
      - static_value:/opt/app/static
      - media_value:/opt/app/media
    depends_on:
      - db
    command: ["./wait-for-db.sh"]

  es:
    image: elasticsearch:7.17.8
    depends_on:
      - backend
    restart: always
    volumes:
      - es_datas:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    ports:
      - "9200:9200"

  etl:
    build: postgres_to_es
    restart: always
    env_file:
      - "./.env"
    volumes:
      - checkpoint:/opt/etl/results
    depends_on:
      - es
    command: [ "./wait-for-es.sh" ]

  nginx:
    image: nginx:latest
    depends_on:
      - etl
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/conf.d/site.conf:/etc/nginx/conf.d/default.conf:ro
      - checkpoint:/var/html/etl_value/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    ports:
      - "80:80"

volumes:
  db_datas:
  es_datas:
  checkpoint:
  static_value:
  media_value:
